from PyQt5 import QtCore, QtGui, QtWidgets


class EditWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(900, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.get_test_title = QtWidgets.QLineEdit(self.tab)
        self.get_test_title.setObjectName("get_test_title")
        self.verticalLayout_2.addWidget(self.get_test_title)
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.get_test_topic = QtWidgets.QLineEdit(self.tab)
        self.get_test_topic.setObjectName("get_test_topic")
        self.verticalLayout_2.addWidget(self.get_test_topic)
        self.pb_addTest = QtWidgets.QPushButton(self.tab)
        self.pb_addTest.setObjectName("pb_addTest")
        self.verticalLayout_2.addWidget(self.pb_addTest)
        self.verticalLayout_4.addLayout(self.verticalLayout_2)
        spacerItem = QtWidgets.QSpacerItem(20, 281, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem)
        self.status_bar = QtWidgets.QLabel(self.tab)
        self.status_bar.setText("")
        self.status_bar.setObjectName("status_bar")
        self.verticalLayout_4.addWidget(self.status_bar)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pb_exit_edit = QtWidgets.QPushButton(self.tab)
        self.pb_exit_edit.setObjectName("pb_exit_edit")
        self.horizontalLayout_4.addWidget(self.pb_exit_edit)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.tab_2)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.choose_test = QtWidgets.QComboBox(self.tab_2)
        self.choose_test.setObjectName("choose_test")
        self.horizontalLayout_2.addWidget(self.choose_test)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pb_addQuestion = QtWidgets.QPushButton(self.tab_2)
        self.pb_addQuestion.setObjectName("pb_addQuestion")
        self.horizontalLayout.addWidget(self.pb_addQuestion)
        self.pb_delete = QtWidgets.QPushButton(self.tab_2)
        self.pb_delete.setObjectName("pb_delete")
        self.horizontalLayout.addWidget(self.pb_delete)
        spacerItem2 = QtWidgets.QSpacerItem(358, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.label_4 = QtWidgets.QLabel(self.tab_2)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.tableView = QtWidgets.QTableWidget(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(170)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableView.sizePolicy().hasHeightForWidth())
        self.tableView.setSizePolicy(sizePolicy)
        self.tableView.setColumnCount(0)
        self.tableView.setObjectName("tableView")
        self.tableView.setRowCount(0)
        self.tableView.horizontalHeader().setDefaultSectionSize(170)
        self.tableView.horizontalHeader().setMinimumSectionSize(170)
        self.verticalLayout.addWidget(self.tableView)
        self.status_bar_2 = QtWidgets.QLabel(self.tab_2)
        self.status_bar_2.setText("")
        self.status_bar_2.setObjectName("status_bar_2")
        self.verticalLayout.addWidget(self.status_bar_2)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.pb_exit_edit_2 = QtWidgets.QPushButton(self.tab_2)
        self.pb_exit_edit_2.setObjectName("pb_exit_edit_2")
        self.horizontalLayout_5.addWidget(self.pb_exit_edit_2)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem3)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.tabWidget.addTab(self.tab_2, "")
        self.verticalLayout_3.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 900, 20))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Редактирование"))
        self.label.setText(_translate("MainWindow", "Название:"))
        self.label_2.setText(_translate("MainWindow", "Тема:"))
        self.pb_addTest.setText(_translate("MainWindow", "ДОБАВИТЬ"))
        self.pb_exit_edit.setText(_translate("MainWindow", "Назад"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Добавить тест"))
        self.label_3.setText(_translate("MainWindow", "Тест:"))
        self.pb_addQuestion.setText(_translate("MainWindow", "Добавить вопрос"))
        self.pb_delete.setText(_translate("MainWindow", "Удалить вопрос"))
        self.label_4.setText(_translate("MainWindow", "Вопросы:"))
        self.pb_exit_edit_2.setText(_translate("MainWindow", "Назад"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Редактировать тест"))
