from PyQt5 import QtCore, QtGui, QtWidgets


class EnterWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(292, 322)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.QWidget = QtWidgets.QTabWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.QWidget.setFont(font)
        self.QWidget.setObjectName("QWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.get_login = QtWidgets.QLineEdit(self.tab)
        self.get_login.setObjectName("get_login")
        self.verticalLayout.addWidget(self.get_login)
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.get_password = QtWidgets.QLineEdit(self.tab)
        self.get_password.setObjectName("get_password")
        self.verticalLayout.addWidget(self.get_password)
        self.pb_enter = QtWidgets.QPushButton(self.tab)
        self.pb_enter.setObjectName("pb_enter")
        self.verticalLayout.addWidget(self.pb_enter)
        self.status_bar = QtWidgets.QLabel(self.tab)
        self.status_bar.setText("")
        self.status_bar.setObjectName("status_bar")
        self.verticalLayout.addWidget(self.status_bar)
        self.QWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_4 = QtWidgets.QLabel(self.tab_2)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.get_login_2 = QtWidgets.QLineEdit(self.tab_2)
        self.get_login_2.setObjectName("get_login_2")
        self.verticalLayout_2.addWidget(self.get_login_2)
        self.label_3 = QtWidgets.QLabel(self.tab_2)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.get_name = QtWidgets.QLineEdit(self.tab_2)
        self.get_name.setObjectName("get_name")
        self.verticalLayout_2.addWidget(self.get_name)
        self.label_5 = QtWidgets.QLabel(self.tab_2)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_2.addWidget(self.label_5)
        self.get_password_2 = QtWidgets.QLineEdit(self.tab_2)
        self.get_password_2.setObjectName("get_password_2")
        self.verticalLayout_2.addWidget(self.get_password_2)
        self.pb_enter_2 = QtWidgets.QPushButton(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pb_enter_2.setFont(font)
        self.pb_enter_2.setObjectName("pb_enter_2")
        self.verticalLayout_2.addWidget(self.pb_enter_2)
        self.status_bar_2 = QtWidgets.QLabel(self.tab_2)
        self.status_bar_2.setText("")
        self.status_bar_2.setObjectName("status_bar_2")
        self.verticalLayout_2.addWidget(self.status_bar_2)
        self.QWidget.addTab(self.tab_2, "")
        self.verticalLayout_3.addWidget(self.QWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 292, 20))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.QWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Вход"))
        self.label.setText(_translate("MainWindow", "Логин"))
        self.label_2.setText(_translate("MainWindow", "Пароль"))
        self.pb_enter.setText(_translate("MainWindow", "ВВОД"))
        self.QWidget.setTabText(self.QWidget.indexOf(self.tab), _translate("MainWindow", "Войти"))
        self.label_4.setText(_translate("MainWindow", "Логин"))
        self.label_3.setText(_translate("MainWindow", "Имя"))
        self.label_5.setText(_translate("MainWindow", "Пароль"))
        self.pb_enter_2.setText(_translate("MainWindow", " ВВОД"))
        self.QWidget.setTabText(self.QWidget.indexOf(self.tab_2), _translate("MainWindow", "Зарегестрироваться"))
